version: '3.8'

services:
  orchestrator:
    build: .
    container_name: gpu-ssh-orchestrator
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/workspaces:/srv/workspaces
      - /var/lib/orchestrator:/var/lib/orchestrator
      - ssh_keys:/shared/ssh_keys
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    restart: unless-stopped

volumes:
  orchestrator_data:
  ssh_keys: 