# GPU 컨테이너 오케스트레이터 기본 설정

# 서버 설정
server:
  port: 8080
  host: "0.0.0.0"

# 데이터베이스 설정
database:
  path: "orchestrator.db"
  max_connections: 10

# Docker 설정
docker:
  base_image: "ubuntu:24.04"
  network_name: "worknet"
  network_subnet: "172.30.0.0/16"
  workspace_root: "/srv/workspaces"

# SSHPiper 설정
sshpiper:
  config_dir: "/etc/sshpiper"
  container_name: "sshpiper"

# GPU 설정
gpu:
  nvml_library_path: "/usr/lib/x86_64-linux-gnu/libnvidia-ml.so"
  mig_profiles:
    - name: "1g.5gb"
      compute_size: 1
      memory_size: 5
    - name: "2g.10gb"
      compute_size: 2
      memory_size: 10
    - name: "3g.20gb"
      compute_size: 3
      memory_size: 20
    - name: "4g.20gb"
      compute_size: 4
      memory_size: 20
    - name: "7g.40gb"
      compute_size: 7
      memory_size: 40

# 세션 설정
session:
  default_ttl_minutes: 60
  max_ttl_minutes: 1440  # 24시간
  cleanup_interval: "1m"
  max_sessions_per_user: 1

# 보안 설정
security:
  container_capabilities:
    drop: ["ALL"]
    add: ["SETGID", "SETUID"]
  container_security_opts:
    - "no-new-privileges:true"

# 로깅 설정
logging:
  level: "info"
  format: "json"
  output: "stdout"

# 모니터링 설정
monitoring:
  prometheus:
    enabled: true
    port: 9090
  metrics:
    enabled: true
    path: "/metrics" 